name: Kevin Takashi Cohen
favicon: null
layout_spectrum: 0.5390054550953209
typography_spectrum: 0.35044354456476867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6188886924646795
  lightness: 0.9143391964025795
  saturation: 0.8554447398055345
  rhythmicContrast: 0.677752181654796
purpose: []
